name: hprofile_workflow
on: workflow_dispatch
jobs:
  testing_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Set Java 11
        uses: actions/setup-java@v5
        with:
         distribution: 'temurin' # See 'Supported distributions' for available options
         java-version: '11'
      - name: Maven Test
        run: mvn test
      - name: Checkstyle
        run: mvn checkstyle:checkstyle
      - run: ls -l
  
