name: Hprofile Actions      #name-of-the-workflow. This name appears in the action tab.
on: workflow_dispatch       #mention-what-will-trigger-the-workflow
jobs:
  Testing:                  #name-of-the-job
    runs-on: ubuntu-latest   #specify-on-which-runner-you-need-to-run-this-job
    steps:
      - name: Code Checkout   
        uses: actions/checkout@v6   #checkout-the-code-to-the-runner
      
      - name: Maven Test
        run: mvn test   #run-the-maven-test-command

      - name: Checkstyle
        run: mvn checkstyle:checkstyle   #run-the-maven-checkstyle-command